# scripts/evaluate.py
"""
RAG Evaluation Harness
======================
This script automates the testing of the RAG pipeline.

Flow:
1. Ingests a known document (data/test_policy.txt) to ensure the database has the right context.
2. Loads a dataset of test questions and expected answers (data/eval_dataset.json).
3. Asks the RAGService each question.
4. Uses the LLMService (Gemini) as a "Judge" to compare the RAG's actual answer against the expected answer.
5. Outputs a final accuracy score.
"""

import asyncio
import json
import os
from pathlib import Path

from google.genai import types

from app.db.database import get_session_factory, init_db
from app.repositories.document_repository import DocumentRepository
from app.services.ingestion_service import IngestionService
from app.services.rag_service import RAGService
from app.services.llm_service import LLMService

JUDGE_PROMPT = """You are an impartial evaluator grading a Retrieval-Augmented Generation (RAG) AI system.
You will be provided with a Question, an Expected Answer (the ground truth), and the Actual Answer generated by the AI.

Your job is to determine if the Actual Answer is correct based on the Expected Answer.
- If the Actual Answer contains the core facts of the Expected Answer, it is a PASS.
- If the Actual Answer is completely wrong, contradicts the expected answer, or gives a factual answer when it was expected to refuse, it is a FAIL.

Respond ONLY with a JSON object in this exact format:
{
    "grade": "PASS" or "FAIL",
    "reasoning": "A one sentence explanation of why you gave this grade."
}
"""

async def ingest_test_document():
    """Ensure the test policy document is ingested into the database."""
    print("--- 1. Preparing Test Environment ---")
    doc_path = Path("data/test_policy.txt")
    if not doc_path.exists():
        raise FileNotFoundError(f"Missing test document: {doc_path}")
        
    with open(doc_path, "rb") as f:
        file_bytes = f.read()
        
    session_factory = get_session_factory()
    async with session_factory() as session:
        repository = DocumentRepository(session)
        ingestion_service = IngestionService(repository)
        
        # Check if we already uploaded it to avoid duplicates
        import hashlib
        sha256_hash = hashlib.sha256(file_bytes).hexdigest()
        existing = await repository.get_by_hash(sha256_hash)
        
        if existing:
            print("Test document 'test_policy.txt' is already in the database. Proceeding to evaluation...")
            return
            
        print("Ingesting 'test_policy.txt'...")
        await ingestion_service.ingest(
            file_bytes=file_bytes,
            filename="test_policy.txt",
            content_type="text/plain",
            description="Automated test document"
        )
        # Commit the transaction so chunks are visible
        await session.commit()
        print("Ingestion complete.")

async def evaluate_rag():
    print("\n--- 2. Running Evaluation ---")
    
    # Load dataset
    dataset_path = Path("data/eval_dataset.json")
    with open(dataset_path, "r") as f:
        dataset = json.load(f)
        
    llm_service = LLMService()
    
    if not llm_service.client:
        print("ERROR: GEMINI_API_KEY is not set in environment. Cannot evaluate.")
        return

    total_questions = len(dataset)
    passed_questions = 0
    
    session_factory = get_session_factory()
    async with session_factory() as session:
        repository = DocumentRepository(session)
        rag_service = RAGService(repository)
        
        for i, test_case in enumerate(dataset, 1):
            question = test_case["question"]
            expected_answer = test_case["expected_answer"]
            
            print(f"\n[Test {i}/{total_questions}]: {question}")
            
            try:
                # 1. Ask RAG
                rag_response = await rag_service.chat(question=question)
                actual_answer = rag_response.answer
                
                print(f"RAG Answer: {actual_answer}")
                
                # 2. Ask Gemini to Judge
                judge_user_prompt = (
                    f"Question: {question}\n\n"
                    f"Expected Answer: {expected_answer}\n\n"
                    f"Actual Answer: {actual_answer}"
                )
                
                judge_response = llm_service.client.models.generate_content(
                    model="gemini-3.6-flash",
                    contents=judge_user_prompt,
                    config=types.GenerateContentConfig(
                        system_instruction=JUDGE_PROMPT,
                        temperature=0.0,
                        response_mime_type="application/json"
                    )
                )
                
                grade_data = json.loads(judge_response.text)
                grade = grade_data.get("grade", "FAIL")
                reasoning = grade_data.get("reasoning", "No reasoning provided.")
                
                if grade == "PASS":
                    passed_questions += 1
                    print(f"[PASS] {reasoning}")
                else:
                    print(f"[FAIL] {reasoning}")
                    print(f"   Expected: {expected_answer}")
                    
            except Exception as e:
                print(f"[ERROR] processing test case: {e}")
                
    # 3. Final Report
    print("\n--- 3. Final Evaluation Report ---")
    accuracy = (passed_questions / total_questions) * 100
    print(f"Score: {passed_questions}/{total_questions} ({accuracy:.1f}%)")
    
    if accuracy == 100.0:
        print("[PERFECT SCORE] Your RAG pipeline is extremely accurate.")
    elif accuracy >= 80.0:
        print("[GOOD SCORE] Good score, but there is room for improvement.")
    else:
        print("[POOR ACCURACY] You may need to tune your chunk size, overlap, or LLM prompt.")

async def main():
    await init_db()
    await ingest_test_document()
    await evaluate_rag()

if __name__ == "__main__":
    asyncio.run(main())
